# Generated by Django 5.1.6 on 2025-02-27 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('photo', models.ImageField(upload_to='assignments/')),
                ('client_logo', models.ImageField(upload_to='client_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='contact/')),
            ],
        ),
        migrations.CreateModel(
            name='CoreCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('introduction', models.TextField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='practice_areas/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='practice_areas_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=50)),
                ('report_summary', models.TextField(max_length=100)),
                ('report_cover', models.ImageField(upload_to='reports/')),
                ('report_file', models.FileField(upload_to='reports/')),
            ],
        ),
        migrations.CreateModel(
            name='RecentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=255)),
                ('contract_duration', models.CharField(max_length=255)),
                ('contract_with', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='projects/')),
                ('logo', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=100)),
                ('images', models.ImageField(blank=True, null=True, upload_to='subareas/')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Core Team', 'Core Team'), ('Technical Expert', 'Technical Expert'), ('International Consultant', 'International Consultant')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('photo', models.ImageField(upload_to='team/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('work_description', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(max_length=200)),
                ('company_profile', models.FileField(upload_to='company_profile/')),
                ('logo', models.ImageField(upload_to='logos/')),
                ('company_name', models.CharField(max_length=50)),
                ('partnership_area', models.CharField(max_length=50)),
                ('core_competencies', models.ManyToManyField(to='core.corecompetency')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='milestones/')),
                ('practice_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.practicearea')),
            ],
        ),
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField(max_length=150)),
                ('organization_development', models.TextField(max_length=100)),
                ('research_evaluation', models.TextField(max_length=100)),
                ('sub_areas', models.ManyToManyField(to='core.subarea')),
            ],
        ),
        migrations.CreateModel(
            name='WorkReach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(max_length=100)),
                ('country', models.CharField(max_length=30)),
                ('assignment_name', models.CharField(max_length=50)),
                ('assignment_photo', models.ImageField(upload_to='work_reach/')),
                ('highlight_assignments', models.ManyToManyField(to='core.assignment')),
            ],
        ),
    ]
