# Generated by Django 5.1.6 on 2025-03-11 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contracts_international_agencies', models.IntegerField()),
                ('us_government_project', models.IntegerField()),
                ('organizational_capacity_assessment', models.IntegerField()),
                ('research_evaluation_assignments', models.IntegerField()),
                ('years_of_experience', models.IntegerField()),
                ('about_text', models.TextField(max_length=200)),
                ('od_text', models.TextField(max_length=300)),
                ('od_image', models.ImageField(upload_to='company_profile/')),
                ('re_text', models.TextField()),
                ('re_image', models.ImageField(upload_to='company_profile/')),
                ('practice_caption', models.TextField()),
            ],
            options={
                'verbose_name_plural': '                 Company Profile',
            },
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('cell', models.CharField(max_length=20)),
                ('website', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Contact Details',
            },
        ),
        migrations.CreateModel(
            name='CoreCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '             Core Competencies',
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_banner/')),
                ('caption', models.TextField()),
            ],
            options={
                'verbose_name_plural': '                Home Banners',
            },
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photo_gallery/')),
            ],
            options={
                'verbose_name_plural': ' Photo Gallery',
            },
        ),
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('introduction', models.TextField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='practice_areas/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='practice_areas/')),
            ],
            options={
                'verbose_name_plural': '      Practice Areas',
            },
        ),
        migrations.CreateModel(
            name='RecentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=255)),
                ('assignment_start', models.DateField()),
                ('assignment_end', models.DateField()),
                ('assignment_with', models.CharField(max_length=255)),
                ('assignment_description', models.TextField(max_length=200)),
                ('assignment_photo', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
            options={
                'verbose_name_plural': '               Recent Projects',
            },
        ),
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': '  Request Forms',
            },
        ),
        migrations.CreateModel(
            name='StrategicPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='partners/')),
                ('company_name', models.CharField(max_length=255)),
                ('company_website_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '          Strategic Partners',
            },
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('OD', 'Organization Development'), ('RE', 'Research & Evaluation')], max_length=2)),
                ('description', models.TextField(max_length=200)),
                ('images', models.ImageField(blank=True, null=True, upload_to='subarea_images/')),
            ],
            options={
                'verbose_name_plural': '         Sub Areas',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Core Team', 'Core Team'), ('Technical Expert', 'Technical Expert'), ('International Consultant', 'International Consultant')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=100)),
                ('photo', models.ImageField(upload_to='team_members/')),
            ],
            options={
                'verbose_name_plural': '     Team Members',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(max_length=150)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': '              Testimonials',
            },
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcontinent', models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Oceania', 'Oceania'), ('Middle East', 'Middle East'), ('Caribbean', 'Caribbean')], max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('work_description', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '   Work Locations',
            },
        ),
        migrations.CreateModel(
            name='YearRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_range', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': '            Year Ranges',
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(max_length=200)),
                ('our_mission_text', models.TextField(max_length=200)),
                ('vision_text', models.TextField(max_length=200)),
                ('integrity_text', models.TextField(max_length=80)),
                ('commitment_text', models.TextField(max_length=80)),
                ('ethical_text', models.TextField(max_length=80)),
                ('inclusivity_text', models.TextField(max_length=80)),
                ('company_profile', models.FileField(upload_to='company_profile_pdfs/')),
                ('logo', models.ImageField(upload_to='logos/')),
                ('company_name', models.CharField(max_length=50)),
                ('core_competencies', models.ManyToManyField(to='core.corecompetency')),
            ],
            options={
                'verbose_name_plural': '             About Us',
            },
        ),
        migrations.CreateModel(
            name='MilestoneWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='milestones/')),
                ('practice_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.practicearea')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField(max_length=150)),
                ('organization_development', models.TextField(max_length=100)),
                ('organization_development_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('research_evaluation', models.TextField(max_length=100)),
                ('research_evaluation_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('sub_areas', models.ManyToManyField(to='core.subarea')),
            ],
            options={
                'verbose_name_plural': '       Service Intros',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('od1', 'OD1'), ('od2', 'OD2'), ('re1', 'RE1'), ('re2', 'RE2')], max_length=3)),
                ('sub_service', models.CharField(max_length=255)),
                ('practice_area', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='assignment_photos/')),
                ('description', models.TextField(max_length=300)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('sub_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.subarea')),
            ],
            options={
                'verbose_name_plural': '        Assignments',
            },
        ),
        migrations.CreateModel(
            name='HistoryTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='history_timeline/')),
                ('year_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='core.yearrange')),
            ],
            options={
                'verbose_name_plural': '           History Timelines',
            },
        ),
    ]
