# Generated by Django 5.1.6 on 2025-02-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': '   About - About Us'},
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': '       Our Work - Assignment'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '           Contact'},
        ),
        migrations.AlterModelOptions(
            name='corecompetency',
            options={'verbose_name': '   About - Core Competency'},
        ),
        migrations.AlterModelOptions(
            name='homebanner',
            options={'verbose_name': '  Home - Banner'},
        ),
        migrations.AlterModelOptions(
            name='milestonework',
            options={'verbose_name': '     Practice Areas - Milestone Work'},
        ),
        migrations.AlterModelOptions(
            name='photogallery',
            options={'verbose_name': '          Photo Gallery'},
        ),
        migrations.AlterModelOptions(
            name='practicearea',
            options={'verbose_name': '     Practice Areas'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '        Our Products'},
        ),
        migrations.AlterModelOptions(
            name='recentproject',
            options={'verbose_name': '  Home - Recent Project'},
        ),
        migrations.AlterModelOptions(
            name='requestform',
            options={'verbose_name': '         Request Form'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '    Services - Our Services'},
        ),
        migrations.AlterModelOptions(
            name='subarea',
            options={'verbose_name': '    Services - Sub Area'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': '      Our Team'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': '  Home - Testimonial'},
        ),
        migrations.AlterModelOptions(
            name='worklocation',
            options={'verbose_name': '  Home - Work Location'},
        ),
        migrations.AlterModelOptions(
            name='workreach',
            options={'verbose_name': '       Our Work - Work Reach'},
        ),
    ]
