# Generated by Django 5.1.6 on 2025-03-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_assignment_sub_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='service_type',
            field=models.CharField(choices=[('Organizational Capacity Assesment', 'Organizational Capacity Assesment'), ('Change Management', 'Change Management'), ('Training & Facilitation', 'Training & Facilitation'), ('Project Cycle Management', 'Project Cycle Management'), ('ICT/MIS Development', 'ICT/MIS Development'), ('Baseline & Program Evaluation', 'Baseline & Program Evaluation'), ('Project Program Evaluation', 'Project Program Evaluation'), ('Market Survey', 'Market Survey'), ('Thematic Research', 'Thematic Research'), ('Impact Assesment', 'Impact Assesment'), ('Performance Studies', 'Performance Studies'), ('Preception Studies', 'Preception Studies')], max_length=255),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='sub_service',
            field=models.CharField(choices=[('OD', 'Organization Development'), ('RE', 'Research & Evaluation')], max_length=2),
        ),
    ]
