# Generated by Django 5.1.6 on 2025-03-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_assignment_service_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestonework',
            options={'verbose_name_plural': '        Assignments'},
        ),
        migrations.RemoveField(
            model_name='milestonework',
            name='image',
        ),
        migrations.AddField(
            model_name='milestonework',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='milestonework',
            name='photo',
            field=models.ImageField(default=1, upload_to='assignment_photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milestonework',
            name='service_type',
            field=models.CharField(choices=[('', 'Select Type'), ('OD', 'Organization Development'), ('RE', 'Research & Evaluation')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milestonework',
            name='sub_service',
            field=models.CharField(choices=[('Organizational Capacity Assesment', 'Organizational Capacity Assesment'), ('Change Management', 'Change Management'), ('Training & Facilitation', 'Training & Facilitation'), ('Project Cycle Management', 'Project Cycle Management'), ('ICT/MIS Development', 'ICT/MIS Development'), ('Baseline & Program Evaluation', 'Baseline & Program Evaluation'), ('Project Program Evaluation', 'Project Program Evaluation'), ('Market Survey', 'Market Survey'), ('Thematic Research', 'Thematic Research'), ('Impact Assesment', 'Impact Assesment'), ('Performance Studies', 'Performance Studies'), ('Preception Studies', 'Preception Studies')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milestonework',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='service_type',
            field=models.CharField(choices=[('', 'Select Type'), ('OD', 'Organization Development'), ('RE', 'Research & Evaluation')], max_length=2),
        ),
        migrations.AlterField(
            model_name='milestonework',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
