# Generated by Django 5.1.6 on 2025-03-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_milestonework_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestonework',
            options={'verbose_name_plural': '        Milestones'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
