# Generated by Django 5.1.6 on 2025-03-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_milestonework_options_teammember_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearrange',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
