# Generated by Django 5.1.6 on 2025-03-15 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_yearrange_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('OD', 'Organization Development'), ('RE', 'Research & Evaluation')], max_length=2)),
                ('description', models.TextField(max_length=200)),
                ('images', models.ImageField(blank=True, null=True, upload_to='subarea_images/')),
            ],
            options={
                'verbose_name_plural': '         Sub Areas',
            },
        ),
        migrations.DeleteModel(
            name='SubArea',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='sub_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subservicearea'),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='sub_areas',
            field=models.ManyToManyField(to='core.subservicearea'),
        ),
    ]
