# Generated by Django 5.1.6 on 2025-03-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_subservicearea_delete_subarea_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='sub_service',
            new_name='sub_service_area',
        ),
    ]
