# Generated by Django 5.1.6 on 2025-03-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_sub_service_assignment_sub_service_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='od_image',
            new_name='organization_development_image',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='od_text',
            new_name='organization_development_text',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='re_image',
            new_name='research_evaluation_image',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='re_text',
            new_name='research_evaluation_text',
        ),
    ]
