# Generated by Django 5.1.6 on 2025-03-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_od_image_companyprofile_organization_development_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial_photo'),
        ),
    ]
