# Generated by Django 5.1.6 on 2025-03-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_testimonial_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='our_mission_text',
            new_name='our_mission',
        ),
    ]
