# Generated by Django 5.1.6 on 2025-03-15 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_strategicpartner_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestonework',
            name='sub_service',
        ),
        migrations.AddField(
            model_name='milestonework',
            name='sub_service_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.subservicearea'),
            preserve_default=False,
        ),
    ]
