# Generated by Django 5.1.6 on 2025-03-15 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_milestonework_sub_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('publication_date', models.DateTimeField()),
                ('tags', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Blog Posts',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('report_pdf', models.FileField(upload_to='reports/')),
            ],
            options={
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.AddField(
            model_name='requestform',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_forms', to='core.report'),
        ),
    ]
