# Generated by Django 5.1.6 on 2025-03-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_blogpost_report_requestform_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_text',
            field=models.TextField(),
        ),
    ]
