# Generated by Django 5.1.6 on 2025-03-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_about_about_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='commitment_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='ethical_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='inclusivity_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='integrity_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='our_mission',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='vision_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='about_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='organization_development_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='corecompetency',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historytimeline',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='milestonework',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='introduction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recentproject',
            name='assignment_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='intro_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='organization_development',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='serviceintro',
            name='research_evaluation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subservicearea',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='statement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='worklocation',
            name='work_description',
            field=models.TextField(),
        ),
    ]
