# Generated by Django 5.1.6 on 2025-03-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_about_commitment_text_alter_about_ethical_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=1, upload_to='blog_photos/'),
            preserve_default=False,
        ),
    ]
