# Generated by Django 5.1.6 on 2025-03-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='core_value_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
