# Generated by Django 5.1.6 on 2025-03-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_about_core_value_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='select_client',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
