# Generated by Django 5.1.6 on 2025-03-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_assignment_select_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photogallery',
            options={'verbose_name_plural': 'Photo Gallery'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
