# Generated by Django 5.1.6 on 2025-03-22 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_photogallery_options_teammember_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='core_competencies',
        ),
    ]
